### ISSUE TITLE
[Feature Request] Execute console commands in notebook

### ISSUE THREAD

**Issue by flomickl** [Yuki-Inoue/jupyter_on_rails#31]
Hi

I asked a question in stack overflow (https://stackoverflow.com/q/65580820/6244257) how to execute bash commands like `rails routes` or generate commands inside my rails notebook.

My solution is to have following method in the beginning of my notebook

```
def execute_console(input)
  %x(#{input}).each_line(chomp: true){|s| p s}
  return nil
end
```

So far I have no clue how I can add this automatically or add this here to create a pull request but I think like the `to_df` command is my maybe possible to implement a similar method for bash commands??? 

I think this would be a nice feature for working in rails notebooks

**Comment by Yuki-Inoue** [comment]
Hi @flomickl , thank you for making request.

I think what you want is some sort of magic command (e.g. [shell magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-script)) supported in https://github.com/SciRuby/iruby .  This library is mainly intended to be the integration layer between iruby and rails, and magic command would be rather iruby's feature alone.

Since python jupyter kernel supports it, if jupyter + ruby ecosystem is to implement some similar feature, I think it should be implemented in the same layer as that of python...
